services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-arena-app
    environment:
      OCR_ARENA_CONFIG: /app/ocr_arena/config.docker.yaml
    volumes:
      - ./models:/app/models
      - ./output:/app/output
    ports:
      - "127.0.0.1:8000:8000"
